### PR TITLE
feat(server): bootstrap server

### PR DESCRIPTION
**Pull request by portellaa**
This is a work in progress.

This is just an idea, i don't like the plugins and the routes yet. 
I'm thinking on moving the routes into a folder outside of the api folder and create an interface for it so they can be dynamically loaded.

What do you guys think? or should we load them statically?

### CODE REVIEW

**Comment by helpImaRock** [comment]
From what I understood,  after reading [Advantages of dynamic vs static routing in React](https://stackoverflow.com/questions/48817305/advantages-of-dynamic-vs-static-routing-in-react), [PWAs](https://en.wikipedia.org/wiki/Progressive_web_application#Characteristics), maybe we should go with dynamic loading, since:

- separates routing logic from routes
- responsive routes ( different client screens )
- code splitting

although:
- impact on client side (pwas?)
- server load?

**Comment by TiagoFilipeSousaGoncalves** [comment]
I prefer dynamic loading as well! Nice work!

**Comment by portellaa** [comment]
@b1zCode this is not a client side app (reactjs or pwa), those advantages or disadvantages doesn't apply here.
the advantage here is that we don't need to go to server.ts file and the route there, the code will look into the routes folder and configure them.

but i prefer it for now too, so let me make that change 😉

**Review by ruimartinsptl — APPROVED** [review]
Looks good to me...

**Comment by helpImaRock** [comment]
> @b1zCode this is not a client side app (reactjs or pwa), those advantages or disadvantages doesn't apply here.
> the advantage here is that we don't need to go to server.ts file and the route there, the code will look into the routes folder and configure them.
> 
> but i prefer it for now too, so let me make that change wink
 
It's going to talk to one, which have UI layout differences between them at least and maybe even usability and functional differences. So, it might be useful to reply with different routes on different clients, hence the responsive routes. But if it is completely client agnostic.. Either way, looks like the best approach

**Comment by portellaa** [comment]
@b1zCode this is an API, the client is going to call those methods, not the opposite. it should be completely agnostic, if in the future we want to support a native app, or any other client, it's completely transparent for us.

**Pull request merged**
